## CONTENT

This Dataset Includes:

### 📊 Dataset Overview
- **Time Period:** Seasons 1999-2020
- **Coverage:** 49 Leagues, ~11K players with details & stats per season

### 👤 Player Details
- Birth Date
- Height & Weight
- Nationality
- High School

### 📈 Season Statistics
- Scoring Stats
- Free Throws
- Rebounds
- Blocks
- Assists
- Minutes Played
- Games Played
- And more...

### 📝 Additional Information
This dataset goes beyond simple rows and columns. It provides comprehensive player information and detailed performance metrics across multiple decades and leagues, making it accessible for analysis and research.

## Importamos y pegamos

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../Data/stats_by_season.csv')

df

,League,Season,Stage,Player,Team,GP,MIN,FGM,FGA,3PM,...,birth_date,height,height_cm,weight,weight_kg,nationality,high_school,draft_round,draft_pick,draft_team
0,NBA,1999 - 2000,Regular_Season,Shaquille O'Neal,LAL,79,3163.0,956,1665,0,...,"Mar 6, 1972",7-1,216.0,325.0,147.0,United States,Robert G. Cole High School,1.0,1.0,Orlando Magic
1,NBA,1999 - 2000,Regular_Season,Vince Carter,TOR,82,3126.0,788,1696,95,...,"Jan 26, 1977",6-6,198.0,220.0,100.0,United States,Mainland High School,1.0,5.0,Golden State Warriors
2,NBA,1999 - 2000,Regular_Season,Karl Malone,UTA,82,2947.0,752,1476,2,...,"Jul 24, 1963",6-9,206.0,265.0,120.0,United States,Summerfield High School,1.0,13.0,Utah Jazz
3,NBA,1999 - 2000,Regular_Season,Allen Iverson,PHI,70,2853.0,729,1733,89,...,"Jun 7, 1975",6-0,183.0,165.0,75.0,United States,Bethel High School,1.0,1.0,Philadelphia Sixers
4,NBA,1999 - 2000,Regular_Season,Gary Payton,SEA,82,3425.0,747,1666,177,...,"Jul 23, 1968",6-4,193.0,180.0,82.0,United States,Skyline High School,1.0,2.0,Seattle SuperSonics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53944,Ukrainian-Superleague,2019 - 2020,International,Kyrylo Meshheryakov,MYK,15,127.0,7,28,2,...,"Aug 17, 1995",6-6,198.0,182.0,83.0,Ukraine,NaN,NaN,NaN,NaN
53945,Ukrainian-Superleague,2019 - 2020,International,Yaroslav Kadygrob,ODE,10,81.7,5,16,4,...,"Oct 28, 1991",6-3,191.0,187.0,85.0,Ukraine,NaN,NaN,NaN,NaN
53946,Ukrainian-Superleague,2019 - 2020,International,Ernesto Tkachuk,ODE,16,124.7,1,15,0,...,"Sep 17, 1994",6-2,188.0,200.0,91.0,Ukraine,NaN,NaN,NaN,NaN
53947,Ukrainian-Superleague,2019 - 2020,International,Andrij Shapovalov,KHAR,12,59.2,0,8,0,...,"Nov 10, 1993",6-2,188.0,171.0,78.0,Ukraine,NaN,NaN,NaN,NaN
53948,Ukrainian-Superleague,2019 - 2020,International,Dmitriy Lypovtsev,KHAR,5,86.3,1,13,0,...,"Oct 10, 1986",6-8,203.0,220.0,100.0,Ukraine,NaN,NaN,NaN,NaN

In [3]:
df.columns

Index(['League', 'Season', 'Stage', 'Player', 'Team', 'GP', 'MIN', 'FGM',
       'FGA', '3PM', '3PA', 'FTM', 'FTA', 'TOV', 'PF', 'ORB', 'DRB', 'REB',
       'AST', 'STL', 'BLK', 'PTS', 'birth_year', 'birth_month', 'birth_date',
       'height', 'height_cm', 'weight', 'weight_kg', 'nationality',
       'high_school', 'draft_round', 'draft_pick', 'draft_team'],
      dtype='str')

#### Descartamos las columnas innecesarias y verificamos si hay algún dato nulo dentro del DF

In [4]:
df = df.drop(columns=['height','weight','birth_month','birth_date'])

In [5]:
df.isnull().any().any()

np.True_

#### Al devolver 'True' nos dice que sí que lo hay. <br> a continuación buscamos en que columna/s están en %

In [6]:
print((df.isnull().sum() / len(df) *100).round(2))

League          0.00
Season          0.00
Stage           0.00
Player          0.00
Team            0.02
GP              0.00
MIN             0.00
FGM             0.00
FGA             0.00
3PM             0.00
3PA             0.00
FTM             0.00
FTA             0.00
TOV             0.00
PF              0.00
ORB             0.00
DRB             0.00
REB             0.00
AST             0.00
STL             0.00
BLK             0.00
PTS             0.00
birth_year      0.59
height_cm       0.14
weight_kg       8.46
nationality     0.01
high_school    56.10
draft_round    81.21
draft_pick     81.21
draft_team     81.21
dtype: float64

In [7]:
df[['Team', 'nationality', 'high_school', 'draft_round', 'draft_pick', 'draft_team']].info()

<class 'pandas.DataFrame'>
RangeIndex: 53949 entries, 0 to 53948
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Team         53938 non-null  str
 1   nationality  53942 non-null  str
 2   high_school  23683 non-null  str
 3   draft_round  10136 non-null  float64
 4   draft_pick   10136 non-null  float64
 5   draft_team   10136 non-null  str
dtypes: float64(2), str(4)
memory usage: 3.9 MB

In [8]:
df['Team'] = df['Team'].fillna('UNK')
df[['nationality', 'high_school']] = df[['nationality', 'high_school']].fillna('Unknown')
df[['draft_round', 'draft_pick']] = df[['draft_round', 'draft_pick']].fillna(np.nan)
df['draft_team'] = df['draft_team'].fillna('Undrafted')

print((df.isnull().sum() / len(df) *100).round(2))

League          0.00
Season          0.00
Stage           0.00
Player          0.00
Team            0.00
GP              0.00
MIN             0.00
FGM             0.00
FGA             0.00
3PM             0.00
3PA             0.00
FTM             0.00
FTA             0.00
TOV             0.00
PF              0.00
ORB             0.00
DRB             0.00
REB             0.00
AST             0.00
STL             0.00
BLK             0.00
PTS             0.00
birth_year      0.59
height_cm       0.14
weight_kg       8.46
nationality     0.00
high_school     0.00
draft_round    81.21
draft_pick     81.21
draft_team      0.00
dtype: float64

In [9]:
df

,League,Season,Stage,Player,Team,GP,MIN,FGM,FGA,3PM,...,BLK,PTS,birth_year,height_cm,weight_kg,nationality,high_school,draft_round,draft_pick,draft_team
0,NBA,1999 - 2000,Regular_Season,Shaquille O'Neal,LAL,79,3163.0,956,1665,0,...,239,2344,1972.0,216.0,147.0,United States,Robert G. Cole High School,1.0,1.0,Orlando Magic
1,NBA,1999 - 2000,Regular_Season,Vince Carter,TOR,82,3126.0,788,1696,95,...,92,2107,1977.0,198.0,100.0,United States,Mainland High School,1.0,5.0,Golden State Warriors
2,NBA,1999 - 2000,Regular_Season,Karl Malone,UTA,82,2947.0,752,1476,2,...,71,2095,1963.0,206.0,120.0,United States,Summerfield High School,1.0,13.0,Utah Jazz
3,NBA,1999 - 2000,Regular_Season,Allen Iverson,PHI,70,2853.0,729,1733,89,...,5,1989,1975.0,183.0,75.0,United States,Bethel High School,1.0,1.0,Philadelphia Sixers
4,NBA,1999 - 2000,Regular_Season,Gary Payton,SEA,82,3425.0,747,1666,177,...,18,1982,1968.0,193.0,82.0,United States,Skyline High School,1.0,2.0,Seattle SuperSonics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53944,Ukrainian-Superleague,2019 - 2020,International,Kyrylo Meshheryakov,MYK,15,127.0,7,28,2,...,3,19,1995.0,198.0,83.0,Ukraine,Unknown,NaN,NaN,Undrafted
53945,Ukrainian-Superleague,2019 - 2020,International,Yaroslav Kadygrob,ODE,10,81.7,5,16,4,...,0,15,1991.0,191.0,85.0,Ukraine,Unknown,NaN,NaN,Undrafted
53946,Ukrainian-Superleague,2019 - 2020,International,Ernesto Tkachuk,ODE,16,124.7,1,15,0,...,1,9,1994.0,188.0,91.0,Ukraine,Unknown,NaN,NaN,Undrafted
53947,Ukrainian-Superleague,2019 - 2020,International,Andrij Shapovalov,KHAR,12,59.2,0,8,0,...,0,3,1993.0,188.0,78.0,Ukraine,Unknown,NaN,NaN,Undrafted
53948,Ukrainian-Superleague,2019 - 2020,International,Dmitriy Lypovtsev,KHAR,5,86.3,1,13,0,...,1,2,1986.0,203.0,100.0,Ukraine,Unknown,NaN,NaN,Undrafted

In [10]:
dff = df.copy()

#### Para los datos nulos que quedan: 'height_cm' 'birth_yea' 'weight_kg' usaremos KNN, <br> puesto que creo que un jugador pivot no medirá lo mismo que un base.

#### Primero estandarizamos y KNN

In [23]:
from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer

cols = ["height_cm", "weight_kg", "birth_year"]

scaler = StandardScaler()
X = scaler.fit_transform(dff[cols])                 # 1. escalar (los NaN se quedan como NaN)
X = KNNImputer(n_neighbors=10).fit_transform(X)    # 2. imputar en escala z
dff[cols] = scaler.inverse_transform(X)

In [24]:
print((dff.isnull().sum() / len(dff) * 100).round(2))

League          0.00
Season          0.00
Stage           0.00
Player          0.00
Team            0.00
GP              0.00
MIN             0.00
FGM             0.00
FGA             0.00
3PM             0.00
3PA             0.00
FTM             0.00
FTA             0.00
TOV             0.00
PF              0.00
ORB             0.00
DRB             0.00
REB             0.00
AST             0.00
STL             0.00
BLK             0.00
PTS             0.00
birth_year      0.00
height_cm       0.00
weight_kg       0.00
nationality     0.00
high_school     0.00
draft_round    81.21
draft_pick     81.21
draft_team      0.00
dtype: float64

#### Queremos ver si hay algún espacio de más en las celdas de las columnas o algún caracter de más.

In [25]:
# Recorremos a ver si hay 

for col in dff.select_dtypes(include='object').columns:
    print(f"\n{col}:")
    print(dff[col].unique()[:10])

League:
<ArrowStringArray>
[                        'NBA',                  'Euroleague',
                     'Eurocup',              'Australian-NBL',
                  'German-BBL', 'Italian-Lega-Basket-Serie-A',
                 'Spanish-ACB',           'French-Jeep-Elite',
          'Argentinian-Liga-A',       'Austrian-A-Bundesliga']
Length: 10, dtype: str

Season:
<ArrowStringArray>
['1999 - 2000', '2000 - 2001', '2001 - 2002', '2002 - 2003', '2003 - 2004',
 '2004 - 2005', '2005 - 2006', '2006 - 2007', '2007 - 2008', '2008 - 2009']
Length: 10, dtype: str

Stage:
<ArrowStringArray>
['Regular_Season', 'Playoffs', 'International']
Length: 3, dtype: str

Player:
<ArrowStringArray>
['Shaquille O'Neal',     'Vince Carter',      'Karl Malone',
    'Allen Iverson',      'Gary Payton', 'Jerry Stackhouse',
       'Grant Hill',    'Kevin Garnett',   'Michael Finley',
     'Chris Webber']
Length: 10, dtype: str

Team:
<ArrowStringArray>
['LAL', 'TOR', 'UTA', 'PHI', 'SEA', 'DET', 'MIN', 'DAL', 'SAC', 'MIL']
Length: 10, dtype: str

nationality:
<ArrowStringArray>
[                   'United States',                          'Germany',
                      'Netherlands',                           'Serbia',
 'Democratic Republic of the Congo',          'United States / Jamaica',
                  'Serbia / Greece',            'United States / Spain',
                'Nigeria / England',                        'Lithuania']
Length: 10, dtype: str

high_school:
<ArrowStringArray>
['Robert G. Cole High School',       'Mainland High School',
    'Summerfield High School',         'Bethel High School',
        'Skyline High School',           'Oak Hill Academy',
    'South Lakes High School',    'Farragut Career Academy',
   'Proviso East High School', 'Detroit Country Day School']
Length: 10, dtype: str

draft_team:
<ArrowStringArray>
[         'Orlando Magic',  'Golden State Warriors',              'Utah Jazz',
    'Philadelphia Sixers',    'Seattle SuperSonics',        'Detroit Pistons',
 'Minnesota Timberwolves',           'Phoenix Suns',      'Charlotte Hornets',
      'San Antonio Spurs']
Length: 10, dtype: str

C:\Users\aleja\AppData\Local\Temp\ipykernel_35272\3228018103.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in dff.select_dtypes(include='object').columns:

#### Vemos que hay espacios de más. Procedemos a eliminarlos: 'Bethel High School ', 'Robert G. Cole High School '

In [26]:
cols_txt = dff.select_dtypes(include='str').columns
dff[cols_txt] = dff[cols_txt].apply(lambda x: x.str.strip())

In [27]:
dff['high_school'].unique()[:10]

<ArrowStringArray>
['Robert G. Cole High School',       'Mainland High School',
    'Summerfield High School',         'Bethel High School',
        'Skyline High School',           'Oak Hill Academy',
    'South Lakes High School',    'Farragut Career Academy',
   'Proviso East High School', 'Detroit Country Day School']
Length: 10, dtype: str

In [28]:
dff

,League,Season,Stage,Player,Team,GP,MIN,FGM,FGA,3PM,...,BLK,PTS,birth_year,height_cm,weight_kg,nationality,high_school,draft_round,draft_pick,draft_team
0,NBA,1999 - 2000,Regular_Season,Shaquille O'Neal,LAL,79,3163.0,956,1665,0,...,239,2344,1972.0,216.0,147.0,United States,Robert G. Cole High School,1.0,1.0,Orlando Magic
1,NBA,1999 - 2000,Regular_Season,Vince Carter,TOR,82,3126.0,788,1696,95,...,92,2107,1977.0,198.0,100.0,United States,Mainland High School,1.0,5.0,Golden State Warriors
2,NBA,1999 - 2000,Regular_Season,Karl Malone,UTA,82,2947.0,752,1476,2,...,71,2095,1963.0,206.0,120.0,United States,Summerfield High School,1.0,13.0,Utah Jazz
3,NBA,1999 - 2000,Regular_Season,Allen Iverson,PHI,70,2853.0,729,1733,89,...,5,1989,1975.0,183.0,75.0,United States,Bethel High School,1.0,1.0,Philadelphia Sixers
4,NBA,1999 - 2000,Regular_Season,Gary Payton,SEA,82,3425.0,747,1666,177,...,18,1982,1968.0,193.0,82.0,United States,Skyline High School,1.0,2.0,Seattle SuperSonics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53944,Ukrainian-Superleague,2019 - 2020,International,Kyrylo Meshheryakov,MYK,15,127.0,7,28,2,...,3,19,1995.0,198.0,83.0,Ukraine,Unknown,NaN,NaN,Undrafted
53945,Ukrainian-Superleague,2019 - 2020,International,Yaroslav Kadygrob,ODE,10,81.7,5,16,4,...,0,15,1991.0,191.0,85.0,Ukraine,Unknown,NaN,NaN,Undrafted
53946,Ukrainian-Superleague,2019 - 2020,International,Ernesto Tkachuk,ODE,16,124.7,1,15,0,...,1,9,1994.0,188.0,91.0,Ukraine,Unknown,NaN,NaN,Undrafted
53947,Ukrainian-Superleague,2019 - 2020,International,Andrij Shapovalov,KHAR,12,59.2,0,8,0,...,0,3,1993.0,188.0,78.0,Ukraine,Unknown,NaN,NaN,Undrafted
53948,Ukrainian-Superleague,2019 - 2020,International,Dmitriy Lypovtsev,KHAR,5,86.3,1,13,0,...,1,2,1986.0,203.0,100.0,Ukraine,Unknown,NaN,NaN,Undrafted

#### Para no tener problemas con los NaN del draft pick y round, creamos una nueva columna con undrafted. <br> Si está Drafteado un 1, si no lo está un 0

In [30]:
dff['drafted'] = df.apply(
    lambda row: 0 if (pd.isna(row['draft_round']) or 
                      pd.isna(row['draft_pick'])  or 
                      row['draft_team'] == 'Undrafted') 
                else 1, axis=1
)

# Verificar
print(dff['drafted'].value_counts())

drafted
0    43813
1    10136
Name: count, dtype: int64

In [31]:
dff

,League,Season,Stage,Player,Team,GP,MIN,FGM,FGA,3PM,...,PTS,birth_year,height_cm,weight_kg,nationality,high_school,draft_round,draft_pick,draft_team,drafted
0,NBA,1999 - 2000,Regular_Season,Shaquille O'Neal,LAL,79,3163.0,956,1665,0,...,2344,1972.0,216.0,147.0,United States,Robert G. Cole High School,1.0,1.0,Orlando Magic,1
1,NBA,1999 - 2000,Regular_Season,Vince Carter,TOR,82,3126.0,788,1696,95,...,2107,1977.0,198.0,100.0,United States,Mainland High School,1.0,5.0,Golden State Warriors,1
2,NBA,1999 - 2000,Regular_Season,Karl Malone,UTA,82,2947.0,752,1476,2,...,2095,1963.0,206.0,120.0,United States,Summerfield High School,1.0,13.0,Utah Jazz,1
3,NBA,1999 - 2000,Regular_Season,Allen Iverson,PHI,70,2853.0,729,1733,89,...,1989,1975.0,183.0,75.0,United States,Bethel High School,1.0,1.0,Philadelphia Sixers,1
4,NBA,1999 - 2000,Regular_Season,Gary Payton,SEA,82,3425.0,747,1666,177,...,1982,1968.0,193.0,82.0,United States,Skyline High School,1.0,2.0,Seattle SuperSonics,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53944,Ukrainian-Superleague,2019 - 2020,International,Kyrylo Meshheryakov,MYK,15,127.0,7,28,2,...,19,1995.0,198.0,83.0,Ukraine,Unknown,NaN,NaN,Undrafted,0
53945,Ukrainian-Superleague,2019 - 2020,International,Yaroslav Kadygrob,ODE,10,81.7,5,16,4,...,15,1991.0,191.0,85.0,Ukraine,Unknown,NaN,NaN,Undrafted,0
53946,Ukrainian-Superleague,2019 - 2020,International,Ernesto Tkachuk,ODE,16,124.7,1,15,0,...,9,1994.0,188.0,91.0,Ukraine,Unknown,NaN,NaN,Undrafted,0
53947,Ukrainian-Superleague,2019 - 2020,International,Andrij Shapovalov,KHAR,12,59.2,0,8,0,...,3,1993.0,188.0,78.0,Ukraine,Unknown,NaN,NaN,Undrafted,0
53948,Ukrainian-Superleague,2019 - 2020,International,Dmitriy Lypovtsev,KHAR,5,86.3,1,13,0,...,2,1986.0,203.0,100.0,Ukraine,Unknown,NaN,NaN,Undrafted,0

#### No tenemos ya ningún dato nulo. Procedemos al guardado del DF

In [32]:
dff.to_csv('../Data/stsbyseasonclean.csv', index=False)